### TETSA POST
POST http://127.0.0.1:5000/device_is_alive.fcgi
Content-Type: application/json

{
    "access_logs": "exemplo de log para testar a API"
}


### TESTA OUTRO POST
POST http://127.0.0.1:5000/device_is_alive.fcgi
Content-Type: application/json

{
    "access_logs": [
        "Log 1: Acesso ao dispositivo às 10:00",
        "Log 2: Configuração alterada às 10:30",
        "Log 3: Usuário desconectou às 11:00"
    ]
}


### TESTA OUTRO POST
POST http://127.0.0.1:5000/device_is_alive.fcgi
Content-Type: application/json

{
    "access_logs": {
        "student_id": "aluno_2024_3004",
        "timestamp": "2024-11-05T10:30:00Z",
        "course_id": "curso_engenharia",
        "module": "Inglês_Instrumental",
        "class_id": "matematica_101",
        "attendance": "ausente"
    }
}


### Requisição GET para obter logs
GET http://127.0.0.1:5000/get_access_logs


